config/routes.rb
Rails.application.routes.draw do

resources :users
resources :photos
resources :sessions

get "/logout", to: "sessions#destroy"
get "photos/vote/:id", to: "photos#vote", as: "submit_vote"

root to: "photos#index"

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
	has_many :hashtag_photos
	has_many :photos, through: :hashtag_photos
end

app/models/hashtag_photo.rb
class HashtagPhoto < ActiveRecord::Base
	belongs_to :hashtag 
	belongs_to :photo
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :photo
	belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	attr_accessor :image
	belongs_to :user
	has_many :likes
	has_many :hashtag_photos
	has_many :hashtags, through: :hashtag_photos

	accepts_nested_attributes_for :hashtags

	mount_uploader :image, PhotoUploader

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true
  	validates :email, presence: true
  	validates :password, presence: true
  	has_secure_password
  	
	has_many :photos
	has_many :likes


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user  
  before_action :auth

  def auth
    unless current_user
      redirect_to new_session_url
    end
  end

  def current_user
    User.find_by(id: session["user_id"])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :auth
	def index
		if !current_user.nil?
			redirect_to photos_url
		else
			render :index
		end
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	skip_before_action :auth, only: [:show, :index]
	def index

		@photos = params[:q].nil? ? Photo.all : Photo.joins(:hashtags).where(hashtags:{name: params[:q]})
	end

	def show
		@photo = Photo.includes(:user).find_by(id: params["id"])
	end

	def vote
		@photo = Photo.find_by(id: params["id"])
		@user = current_user
		@like = Like.find_or_create_by(photo_id: @photo.id, user_id: @user.id)

		@like.save
		redirect_to photos_path

	end

	def new
		@photo = Photo.new
		3.times { @photo.hashtags.build}
	end

	def create
		hashtags_attribute = params[:photo][:hashtags_attributes]
		params[:photo].delete("hashtags_attributes")
		@photo = Photo.new(params[:photo])

		hashtags_attribute.each do |key, attributes|
			if attributes[:name] != ""
				hashtag = Hashtag.find_or_create_by(name: attributes[:name])
				@photo.hashtags << hashtag
			end
		end

		@photo.user = current_user

   		respond_to do |format|
			if @photo.save
				format.html { redirect_to @photo }
			else
				format.html { render :new }
				
			end
		end
	end

	def edit
		@photo = Photo.find_by(id: params["id"])
	end

	def update
		@photo = Photo.find_by(id: params["id"])

   		respond_to do |format|
			if @photo.update(params[:photo])
				format.html { redirect_to @photo }
			else
				format.html { render :new }
				
			end
		end
	end

	def destroy
		@photo = Photo.find_by(id: params["id"])
	    @photo.destroy
		redirect_to photos_url
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :auth
  layout false

  def create
    # params["email"] => the email address
    # params["password"] => the password
    
    @user = User.find_by(email: params["email"])
    if @user.present?
      # Yes, the user exists
      if @user.authenticate(params["password"])
        session["user_id"] = @user.id
        redirect_to root_url
      else
        redirect_to new_session_url, alert: 'User does not exist'
      end
    else
      # No user with that email
      redirect_to new_session_url, alert: 'No user email found'
    end

    # Redirect to the root_path
    # Display a notice that login was either successful or unsuccessful
  end

  def destroy
    session["user_id"] = nil
    redirect_to root_url, notice: "You are logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :auth, only: [:new, :create]

	def index 
		@users = User.all
	end

	def show 
		@user = current_user
	end

	def new
		@user = User.new
	end

	def create
		@user = User.create(params["user"])
		if @user.valid?
		 	redirect_to user_path(@user)
		else
		 	render "new"
		end
	end

	def edit
		@user = current_user
	end

	def update
	    @user = current_user
	    @user.update(params["user"])
	    redirect_to users_path
  	end

	def destroy
		@user = current_user
	    @user.destroy
		redirect_to users_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Landing Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instapix</title>
  <%= javascript_include_tag 'application' %>
  
  <!-- Logo Font -->
    <link href="//fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet" type="text/css">
    
  <!-- Bootstrap -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Font Awesome -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">

      <!-- Alerts -->
      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div
>      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      
      <nav class="navbar navbar-inverse" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to "Instapix", root_url, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a href="/">
                <i class="fa fa-home"></i>
                Home
              </a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

            <% if current_user %>
              <li><%= link_to current_user.try(:name), root_url %></li>
              <li><%= link_to "Logout", logout_url %></li>
            <% else %>
              <li><%= link_to "Sign In", new_session_url %></li>
              <li><%= link_to "Sign Up", new_user_url %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<%= form_for @photo do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
      <%= form.file_field :image %>
      <%= form.label :hashtags %>
      <%= form.fields_for :hashtags do |hashtag_form| %>
          <%= hashtag_form.text_field :name %>
      <% end %>
    </div>
    <%= form.button 'Update Photo', class: "btn btn-success" %>
<% end %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photo_path %>

app/views/photos/index.html.erb
<%= button_to "New Photo", new_photo_path, class: "btn btn-lg btn-primary pull-right", method: "get" %>
<div class="container text-center">
  <% @photos.each do |photo| %>
      <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
          <div class="photo">
            <%= link_to image_tag(photo.image_url().to_s, {class: "img-thumbnail"}), photo_path(photo.id)%>
            <div class="row">
              <div class="col-sm-4 col-md-4 col-lg-4">

              </div>
              <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="name"><%= photo.name %> by <%= photo.user.name %> |
                  <% photo.hashtags.each do |hashtag| %>
                    <%= link_to "##{hashtag.name}", "photos?q=#{hashtag.name}" %>
                  <% end %>
                </div>
              </div>
              <div class="col-sm-4 col-md-4 col-lg-4 text-right">
                <%= link_to( current_user ? submit_vote_path(photo.id) : "javascript:void(0);" ) do %>
                    <i class='fa fa-thumbs-o-up fa-2x like'></i>
                    <% end %>
                <%= photo.likes.count %>
              </div>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<%= form_for @photo, html: {multipart: true} do |form| %>
<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control" %>
  <%= form.file_field :image %>
  <%= form.label :hashtags %>
  <%= form.fields_for :hashtags do |hashtag_form| %>
    <%= hashtag_form.text_field :name %>
  <% end %>

</div>
<%= form.button 'Upload', class: "btn btn-success" %>
<% end %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user && current_user.id == @photo.user.id %>
<%= button_to "Edit Photo", edit_photo_path(@photo), class: "btn btn-lg btn-primary pull-right", method: "get" %>
<% end %>
<%= button_to "Back", photos_path, class: "btn btn-lg btn-primary pull-left", method: "get" %>
<div class="container text-center">
      <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
          <div class="photo">
            <%= image_tag @photo.image_url().to_s, {class: "img-thumbnail"} %>
            <div class="row">
              <div class="col-sm-4 col-md-4 col-lg-4">

              </div>
              <div class="col-sm-4 col-md-4 col-lg-4">
                <div class="name"><%= @photo.name %> by <%= @photo.user.name %> |
                  <% @photo.hashtags.each do |hashtag| %>
                      <%= link_to "##{hashtag.name}", photos_path(q: hashtag.name) %>
                  <% end %>
                </div>
              </div>
              <div class="col-sm-4 col-md-4 col-lg-4 text-right">
                <%= link_to( current_user ? submit_vote_path(@photo.id) : "javascript:void(0);" ) do %>
                    <i class='fa fa-thumbs-o-up fa-2x like'></i>
                <% end %>
                <%= @photo.likes.count %>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>

app/views/users/edit.html.erb
<h1>Edit User Information</h1>

<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>
<%= form.button 'Update User Information', class: "btn btn-success" %>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<h3 class="page-header">
  All Users
  <span class="pull-right">
    <%= link_to "New User", new_user_path, class: 'btn btn-sm btn-success' %>
  </span>
</h3>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %> <%= link_to "Edit", edit_user_path(user) %> <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: 'Are you sure you want to delete user?' } %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

<%= form.button 'Create User', class: "btn btn-success" %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<table>
 <thead>
   <tr>
     <th>Username</th>
     <th>Email</th>
     <th>Location</th>
   </tr>
 </thead>

 <tbody>
     <tr>
       <td><%= @user.name %></td>
       <td><%= @user.email %></td>
       <td><%= @user.location %></td>

     </tr>
 </tbody>
</table>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>